In [1]:
import pandas as pd 
import numpy as np 
import torch.nn as nn
import torch 
from torch.utils.data import DataLoader,Dataset 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

In [2]:
df=pd.read_csv('Social_Network_Ads.csv')
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
df.drop(columns=['User ID'],inplace=True)

In [4]:
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['Purchased']),df['Purchased'],test_size=0.25,shuffle=True,random_state=32)

In [5]:
X_train

     Gender  Age  EstimatedSalary
296    Male   42            73000
18     Male   46            28000
101    Male   28            59000
23   Female   45            22000
374  Female   37            80000
..      ...  ...              ...
380    Male   42            64000
310  Female   42            70000
389  Female   48            35000
43     Male   30            15000
215  Female   60           108000

[300 rows x 3 columns]

In [6]:
X_test

     Gender  Age  EstimatedSalary
223    Male   60           102000
145  Female   24            89000
146  Female   27            96000
366  Female   58            47000
268  Female   47           144000
..      ...  ...              ...
94   Female   29            83000
342  Female   38            65000
180    Male   26            16000
295  Female   36            63000
169  Female   29            47000

[100 rows x 3 columns]

In [7]:
type(X_train['Gender'])

pandas.core.series.Series

In [8]:
ohe=OneHotEncoder(drop='first',sparse_output=False)
X_train_gen=ohe.fit_transform(X_train[['Gender']])
X_test_gen=ohe.transform(X_test[['Gender']])

In [ ]:
X_train_gen

In [ ]:
X_test_gen

In [11]:
# Convert to DataFrames
X_train_gender = pd.DataFrame(
    X_train_gen,
    columns=ohe.get_feature_names_out(['Gender']),
    index=X_train.index
)

X_test_gender = pd.DataFrame(
    X_test_gen,
    columns=ohe.get_feature_names_out(['Gender']),
    index=X_test.index
)

# Drop original Gender column and concatenate encoded column
X_train = pd.concat(
    [X_train.drop(columns=['Gender']), X_train_gender],
    axis=1
)

X_test = pd.concat(
    [X_test.drop(columns=['Gender']), X_test_gender],
    axis=1
)

In [12]:
X_train

     Age  EstimatedSalary  Gender_Male
296   42            73000          1.0
18    46            28000          1.0
101   28            59000          1.0
23    45            22000          0.0
374   37            80000          0.0
..   ...              ...          ...
380   42            64000          1.0
310   42            70000          0.0
389   48            35000          0.0
43    30            15000          1.0
215   60           108000          0.0

[300 rows x 3 columns]

In [13]:
X_test

     Age  EstimatedSalary  Gender_Male
223   60           102000          1.0
145   24            89000          0.0
146   27            96000          0.0
366   58            47000          0.0
268   47           144000          0.0
..   ...              ...          ...
94    29            83000          0.0
342   38            65000          0.0
180   26            16000          1.0
295   36            63000          0.0
169   29            47000          0.0

[100 rows x 3 columns]

In [14]:
X_test=np.array(X_test)
X_train=np.array(X_train)
y_train=np.array(y_train)
y_test=np.array(y_test)

In [15]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [16]:
X_train=torch.tensor(X_train,dtype=torch.float32,requires_grad=True)
X_test=torch.tensor(X_test,dtype=torch.float32,requires_grad=True)
y_train=torch.tensor(y_train,dtype=torch.float32,requires_grad=True)
y_test=torch.tensor(y_test,dtype=torch.float32,requires_grad=True)

In [ ]:
X_train

In [18]:
class CustomDataset(Dataset): 
    def __init__(self,inp,outp):
        self.inp=inp
        self.outp=outp

    def __len__(self):
        return self.inp.shape[0]

    def __getitem__(self,indx):
        return self.inp[indx], self.outp[indx]

In [19]:
dataset=CustomDataset(X_train,y_train)

In [20]:
len(dataset)

300

In [21]:
dataset[0]

(tensor([0.4698, 0.0794, 0.9934], grad_fn=<SelectBackward0>),
 tensor(1., grad_fn=<SelectBackward0>))

In [32]:
dataloader=DataLoader(dataset,batch_size=50,shuffle=True)

In [34]:
dataloader

In [33]:
for batch_inp,batch_out in dataloader: 
    print(batch_inp)
    print(batch_out)
    print('..'*40)

tensor([[ 0.1716,  1.8994, -1.0067],
        [ 0.1716, -0.2787, -1.0067],
        [-0.9216, -0.3383,  0.9934],
        [-0.2259, -0.6069, -1.0067],
        [ 1.7617,  1.7800, -1.0067],
        [ 1.1654, -1.0246, -1.0067],
        [ 1.4636,  2.3768,  0.9934],
        [ 1.0660, -0.8754,  0.9934],
        [-0.0272,  0.0495,  0.9934],
        [ 1.8611,  1.8695,  0.9934],
        [-1.0210, -0.3682,  0.9934],
        [-1.1204,  0.0495, -1.0067],
        [ 0.3704,  0.4971,  0.9934],
        [ 0.1716,  0.1390, -1.0067],
        [ 2.2586,  1.1236, -1.0067],
        [ 1.0660, -1.1141,  0.9934],
        [-0.6235, -1.6511, -1.0067],
        [ 1.0660,  0.1092,  0.9934],
        [ 0.4698, -0.5174, -1.0067],
        [-1.6173, -0.0698, -1.0067],
        [ 0.1716, -0.3383, -1.0067],
        [ 0.9667, -0.6069, -1.0067],
        [ 2.1593,  0.3777, -1.0067],
        [ 1.6623, -0.0101,  0.9934],
        [-1.7167,  0.3479, -1.0067],
        [-0.8222,  0.1390,  0.9934],
        [-1.5179,  0.3181,  0.9934],
        [-1.1204,  0.4076, -1.0067],
        [ 0.4698, -0.0101, -1.0067],
        [-0.7228,  1.3623, -1.0067],
        [-1.8161, -1.5318,  0.9934],
        [-0.8222,  0.2882,  0.9934],
        [-0.7228, -0.2488, -1.0067],
        [-0.7228,  0.5567,  0.9934],
        [-0.2259,  0.5269,  0.9934],
        [-0.1265,  1.6308,  0.9934],
        [ 0.0722,  0.0197,  0.9934],
        [ 0.4698, -0.4875,  0.9934],
        [-0.9216, -1.1439,  0.9934],
        [-0.5241,  1.9292, -1.0067],
        [ 1.0660, -1.2036, -1.0067],
        [ 1.0660,  1.8994, -1.0067],
        [-0.2259,  0.6164,  0.9934],
        [ 0.7679, -1.1439,  0.9934],
        [-0.0272,  0.6761, -1.0067],
        [ 0.4698,  0.0794,  0.9934],
        [-0.6235,  0.1092,  0.9934],
        [-1.6173,  0.5269,  0.9934],
        [ 0.1716,  0.0197,  0.9934],
        [-1.2198, -1.1141,  0.9934]], grad_fn=<StackBackward0>)
tensor([1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1.,
        0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
       grad_fn=<StackBackward0>)
................................................................................
tensor([[-0.0272, -0.2488, -1.0067],
        [-0.5241, -1.5616,  0.9934],
        [-0.6235, -0.0698, -1.0067],
        [-0.0272,  0.1987,  0.9934],
        [-0.9216,  0.4374, -1.0067],
        [ 1.0660, -1.1141,  0.9934],
        [ 0.1716,  0.0197, -1.0067],
        [-0.4247,  1.2728, -1.0067],
        [-0.2259, -0.1593, -1.0067],
        [-1.1204,  1.4220, -1.0067],
        [-0.0272,  0.2882, -1.0067],
        [-0.8222, -0.8157,  0.9934],
        [ 0.7679, -1.3229,  0.9934],
        [ 0.2710, -0.3980,  0.9934],
        [-1.0210,  0.5269,  0.9934],
        [-1.0210, -0.4875, -1.0067],
        [ 0.4698,  0.5866, -1.0067],
        [-0.6235,  0.5567, -1.0067],
        [-1.5179, -0.4577, -1.0067],
        [ 0.7679, -0.7560, -1.0067],
        [ 0.4698,  0.2882,  0.9934],
        [-1.7167,  0.3479, -1.0067],
        [-1.5179, -0.2190, -1.0067],
        [ 1.3642,  1.8994, -1.0067],
        [ 0.0722, -0.4577, -1.0067],
        [-1.6173, -1.6213, -1.0067],
        [-0.2259, -0.2787,  0.9934],
        [ 0.3704,  0.0495, -1.0067],
        [-0.1265, -0.5472,  0.9934],
        [ 0.1716,  1.5413,  0.9934],
        [ 0.0722, -0.6069, -1.0067],
        [-0.0272, -0.5174,  0.9934],
        [-0.2259,  0.1390,  0.9934],
        [-0.4247, -1.2633, -1.0067],
        [-0.1265,  0.8551,  0.9934],
        [ 0.8673,  0.7656, -1.0067],
        [-1.1204, -1.2036,  0.9934],
        [-0.1265,  0.1390, -1.0067],
        [-1.9154, -0.0698, -1.0067],
        [-0.4247,  2.3469, -1.0067],
        [-0.2259,  0.0495,  0.9934],
        [-1.9154,  0.3479,  0.9934],
        [ 0.4698,  0.2882, -1.0067],
        [-0.9216,  0.5567,  0.9934],
        [-0.1265, -1.1141,  0.9934],
        [-1.4185, -1.2633, -1.0067],
        [ 1.0660,  1.4518, -1.0067],
        [-0.2259, -0.3383,  0.9934],
        [ 1.0660, -1.0544, -1.0067],
        [-0.1265,  1.4220,  0.9934]], grad_fn=<StackBackward0>)
tensor([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1.],
       grad_fn=<StackBackward0>)
................................................................................
tensor([[-0.5241,  0.8849,  0.9934],
        [-0.0272, -0.3980, -1.0067],
        [ 0.2710, -0.3980,  0.9934],
        [-0.9216,  1.5712,  0.9934],
        [-0.5241,  2.3768, -1.0067],
        [ 1.9605, -0.3085,  0.9934],
        [-0.1265, -0.4875, -1.0067],
        [ 2.2586, -0.8456,  0.9934],
        [ 0.8673,  0.5269,  0.9934],
        [-0.2259, -1.4423,  0.9934],
        [-0.2259, -1.4124, -1.0067],
        [-0.9216,  0.4971, -1.0067],
        [ 0.9667, -1.3528,  0.9934],
        [-1.8161, -1.4721, -1.0067],
        [-1.9154, -0.5472,  0.9934],
        [ 2.0599, -1.4124, -1.0067],
        [-1.8161, -1.3528,  0.9934],
        [ 0.3704, -0.5472,  0.9934],
        [-0.8222,  2.3171,  0.9934],
        [ 0.1716, -0.8456,  0.9934],
        [-0.7228,  1.9292,  0.9934],
        [-0.7228,  0.4971,  0.9934],
        [ 0.3704, -0.3383,  0.9934],
        [-0.2259, -0.9351,  0.9934],
        [-0.2259, -0.5174,  0.9934],
        [-1.4185, -0.1295, -1.0067],
        [-0.2259, -0.6069,  0.9934],
        [-0.6235,  0.1689,  0.9934],
        [-0.5241,  1.3922, -1.0067],
        [ 0.0722, -0.5770,  0.9934],
        [-0.5241,  1.3922, -1.0067],
        [ 0.2710,  0.1390, -1.0067],
        [ 0.5691,  1.8695, -1.0067],
        [ 0.3704, -1.2036, -1.0067],
        [-1.0210,  0.4076, -1.0067],
        [ 1.5630,  1.0043, -1.0067],
        [-0.6235, -0.1295,  0.9934],
        [ 2.1593,  0.1689, -1.0067],
        [-0.9216, -0.9947, -1.0067],
        [-0.7228,  0.2882,  0.9934],
        [-0.6235,  1.4220, -1.0067],
        [ 1.9605,  0.1092,  0.9934],
        [-1.1204, -1.0544, -1.0067],
        [-0.7228, -1.5915,  0.9934],
        [-0.2259,  1.1236,  0.9934],
        [-0.4247, -0.8157,  0.9934],
        [-1.6173,  0.0495,  0.9934],
        [ 0.0722,  0.0197,  0.9934],
        [-1.3191, -1.2931, -1.0067],
        [ 0.3704, -0.5770, -1.0067]], grad_fn=<StackBackward0>)
tensor([1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0.,
        1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
        0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       grad_fn=<StackBackward0>)
................................................................................
tensor([[-1.2198, -1.4423,  0.9934],
        [ 2.1593,  2.1679,  0.9934],
        [ 0.4698,  0.2584, -1.0067],
        [ 1.4636,  1.3026, -1.0067],
        [-0.3253,  0.0495, -1.0067],
        [-0.6235, -1.5616,  0.9934],
        [-0.0272,  0.0197, -1.0067],
        [ 2.0599,  0.9148, -1.0067],
        [ 0.1716,  1.0640,  0.9934],
        [ 2.0599,  0.7358, -1.0067],
        [-0.2259,  0.7954, -1.0067],
        [ 0.9667, -1.4124,  0.9934],
        [ 0.8673,  0.2584,  0.9934],
        [ 0.4698, -0.1593,  0.9934],
        [ 1.0660,  0.5866,  0.9934],
        [-1.9154, -0.7859, -1.0067],
        [-0.2259,  0.0794,  0.9934],
        [-0.8222,  0.3777, -1.0067],
        [-1.8161,  0.1689,  0.9934],
        [ 0.0722, -0.2787,  0.9934],
        [-0.2259, -0.6964, -1.0067],
        [ 0.9667, -1.0842,  0.9934],
        [ 0.2710,  2.1381, -1.0067],
        [ 1.3642, -1.4124,  0.9934],
        [-1.8161, -1.3229, -1.0067],
        [ 0.2710,  1.0938,  0.9934],
        [ 0.8673, -1.2633,  0.9934],
        [ 1.4636,  2.0187, -1.0067],
        [-0.2259, -0.3085, -1.0067],
        [ 0.4698, -0.1892,  0.9934],
        [-1.7167, -1.4124, -1.0067],
        [-0.9216,  0.2584,  0.9934],
        [ 0.2710, -0.3085, -1.0067],
        [-0.4247, -0.0400, -1.0067],
        [-0.3253,  1.3325,  0.9934],
        [ 2.1593,  0.5269, -1.0067],
        [ 2.2586,  0.3777,  0.9934],
        [ 0.3704,  0.0495, -1.0067],
        [ 0.6685, -0.9351, -1.0067],
        [-0.7228, -1.6511,  0.9934],
        [ 1.2648, -1.0246, -1.0067],
        [-0.1265, -0.3085,  0.9934],
        [-0.2259, -0.3682,  0.9934],
        [ 1.7617,  1.6308, -1.0067],
        [ 2.0599,  2.1977,  0.9934],
        [ 0.1716,  0.7656,  0.9934],
        [-0.4247, -1.1738,  0.9934],
        [ 2.1593,  1.7800,  0.9934],
        [-0.8222, -1.2633, -1.0067],
        [ 0.3704, -0.5472,  0.9934]], grad_fn=<StackBackward0>)
tensor([0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0.,
        0., 0., 0., 1., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1.,
        1., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 1., 0., 0.],
       grad_fn=<StackBackward0>)
................................................................................
tensor([[-1.5179, -1.2931, -1.0067],
        [ 0.8673,  0.1092, -1.0067],
        [-0.2259,  2.2872, -1.0067],
        [-0.1265,  1.6607, -1.0067],
        [-0.0272,  0.2584,  0.9934],
        [-0.1265, -0.6069, -1.0067],
        [-1.3191, -1.1439, -1.0067],
        [ 0.0722, -0.6069, -1.0067],
        [ 0.0722, -0.2787,  0.9934],
        [ 0.1716,  0.1987,  0.9934],
        [ 0.2710,  0.2285,  0.9934],
        [-1.1204, -0.5472, -1.0067],
        [-0.0272,  2.1977,  0.9934],
        [ 0.0722,  1.2430, -1.0067],
        [-0.0272, -0.5472,  0.9934],
        [ 0.9667,  1.0938, -1.0067],
        [ 1.5630,  2.1679, -1.0067],
        [ 0.0722, -0.3383,  0.9934],
        [-0.0272,  0.1092,  0.9934],
        [ 0.3704, -0.3085, -1.0067],
        [-1.3191, -0.3682,  0.9934],
        [ 0.4698,  2.3469,  0.9934],
        [ 1.1654, -0.1593,  0.9934],
        [-0.0272, -1.1141, -1.0067],
        [-0.2259, -1.2931,  0.9934],
        [-1.3191, -1.4124,  0.9934],
        [-1.2198,  0.5866,  0.9934],
        [-0.2259,  0.1390,  0.9934],
        [-1.3191, -0.4577,  0.9934],
        [ 0.9667, -0.6367, -1.0067],
        [ 0.9667, -1.2036, -1.0067],
        [ 0.3704, -0.2190, -1.0067],
        [-0.6235, -1.0842, -1.0067],
        [-1.1204, -0.8157, -1.0067],
        [-1.4185,  0.3479, -1.0067],
        [-0.2259,  0.0495, -1.0067],
        [ 2.1593, -1.2334, -1.0067],
        [ 0.4698, -0.1593,  0.9934],
        [ 0.8673, -1.4124,  0.9934],
        [-0.4247, -0.5770, -1.0067],
        [ 0.8673, -0.8754, -1.0067],
        [-0.0272,  0.1390,  0.9934],
        [ 1.2648, -0.7859, -1.0067],
        [ 0.2710, -0.6964,  0.9934],
        [ 1.0660,  2.1082,  0.9934],
        [-0.0272,  1.9889, -1.0067],
        [-0.0272,  0.2285, -1.0067],
        [ 1.6623, -1.3229, -1.0067],
        [-1.2198,  0.4971,  0.9934],
        [-0.6235,  0.0197, -1.0067]], grad_fn=<StackBackward0>)
tensor([0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.,
        1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0.],
       grad_fn=<StackBackward0>)
................................................................................
tensor([[-1.0210, -0.3980, -1.0067],
        [ 0.4698,  1.0043,  0.9934],
        [-1.1204,  0.3181,  0.9934],
        [-1.9154,  0.4672, -1.0067],
        [ 0.9667, -1.5020,  0.9934],
        [ 1.1654, -0.9351, -1.0067],
        [-1.3191,  0.4076,  0.9934],
        [-0.4247, -0.8754, -1.0067],
        [-0.3253,  1.2430,  0.9934],
        [-1.1204, -1.6511, -1.0067],
        [ 0.4698,  1.1236, -1.0067],
        [-1.1204,  0.2882,  0.9934],
        [-0.9216, -0.3383, -1.0067],
        [ 0.0722,  1.2728, -1.0067],
        [-0.2259, -0.4577,  0.9934],
        [-0.2259,  0.0197, -1.0067],
        [ 2.2586, -0.8456,  0.9934],
        [ 0.3704,  0.2882, -1.0067],
        [ 0.2710,  0.0197,  0.9934],
        [ 0.3704,  0.0197, -1.0067],
        [ 0.2710, -0.3980,  0.9934],
        [ 0.7679, -1.4423,  0.9934],
        [-0.5241,  1.4817,  0.9934],
        [ 1.5630,  0.3479, -1.0067],
        [-1.1204, -1.6511,  0.9934],
        [-0.9216, -0.4577, -1.0067],
        [-1.4185, -0.2190,  0.9934],
        [ 0.3704,  0.0495,  0.9934],
        [ 0.1716,  0.2584, -1.0067],
        [-0.6235, -0.3682,  0.9934],
        [-0.7228,  0.2584, -1.0067],
        [-0.0272,  0.2882, -1.0067],
        [ 0.5691,  1.7502,  0.9934],
        [-0.0272, -0.4577,  0.9934],
        [ 1.6623,  1.0043, -1.0067],
        [ 1.7617, -0.9351,  0.9934],
        [ 0.5691,  1.2430, -1.0067],
        [ 0.2710,  0.0495, -1.0067],
        [ 1.1654, -1.2633,  0.9934],
        [ 0.9667, -0.5770, -1.0067],
        [ 0.7679, -1.4423, -1.0067],
        [-0.3253, -0.8157, -1.0067],
        [-1.7167, -0.6367,  0.9934],
        [ 0.7679,  1.8099, -1.0067],
        [ 1.9605, -1.3229, -1.0067],
        [ 0.1716, -0.8456,  0.9934],
        [-0.2259,  0.2584,  0.9934],
        [ 0.8673,  1.3922,  0.9934],
        [-1.3191, -0.4577, -1.0067],
        [ 0.8673, -0.3383,  0.9934]], grad_fn=<StackBackward0>)
tensor([0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0.,
        1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1.,
        1., 0., 1., 1., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0.],
       grad_fn=<StackBackward0>)
................................................................................